### ISSUE TITLE
client.isAuthenticated always returns true, even without running backend

### ISSUE THREAD

**Issue by rlvdijk** [baasbox/iOS-SDK#29]
I'm using the following piece of code (from the tutorial) to verify if the user is authenticated. 

```
   BAAClient *client = [BAAClient sharedClient];

   if (client.isAuthenticated) {
        NSLog(@"MVC: User %@ logged in", client.currentUser.username);
```
If there's no backend baasbox running on my local OSX machine, the check for isAuthenticated always returns 'true'. So the user is always 'logged in'. Which is clearly not the case. This situation remains the same, even after rebooting. Only when I reset the iOS simulator, I have to log in again. 

It appears isAuthentificated just checks if the session token exists. 

In my opinion, from a functional point of view, being authenticated can only be true when the user credentials (or token) can be validated by a valid and running background server. Otherwise, being authenticated has no real (user) value.

**Comment by funkyboy** [comment]
Well, you might wanna do something with the cached data and update the backend when you are back online.

**Comment by rlvdijk** [comment]
Agree. So you think I should use the suggestion of Stanislav Dmitrenko  and use the local notification of a bad session ?

**Comment by funkyboy** [comment]
You get that notification when the token is expired. If that's your use case yes. You won't get that notification if the device is not online.

**Comment by rlvdijk** [comment]
At the moment I have the situation where isAuthenticated is true, but when I try to e.g. update the user profile, I get an error message suggesting the session has expired.

So I'm quite sure what 'isAuthenticated' means. Can you explain ?

**Comment by funkyboy** [comment]
isAuthenticated means "the last time I logged in I got a valid token and I am gonna use it for subsequent authenticated calls". 
If the server has been restarted that token is not valid anymore and that's why you get the session expired message.

**Comment by rlvdijk** [comment]
Ok, thanks. That makes it more clear. I've added some code in my project to check wether the user needs to login (by using the expired authentication token notification).
