### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by apps4u** [baasbox/iOS-SDK#3]
Hi I can not login in I created a new project added the sdk as a pod and then changed the baseURL and AppCode then in the appDelegate method I tried to login as admin or create a user and neither would work

```
     [[BAAClient sharedClient] authenticateUser:@"admin" password:@"admin" completion:^(BOOL success, NSError *error) {
        if(!error) {
            NSLog(@"done");
        } else {
            NSLog(@"error - %@",error.description);
        }
    }];
```

or 

```
    [[BAAClient sharedClient] createUserWithUsername:@"jason" password:@"monika78" completion:^(BOOL success, NSError *error) {
        if(!error) {
            NSLog(@"done");
        } else {
            NSLog(@"error - %@",error.description);
       }
   }];
```

**Comment by invoodoo** [comment]
I'm getting crash on login too – https://space.zeo.net/g/31p34, first time I run the app it crashed on 

[self postPath:@"login"
        parameters:@{@"username" : username, @"password": password, @"appcode" : self.appCode}
           success:^(NSDictionary *responseObject) {

Second run – everything ok, it was from Xcode 6.0 to 6.3 betas doesn't care.
