### ISSUE TITLE
Crash on first run of the app on login

### ISSUE THREAD

**Issue by invoodoo** [baasbox/iOS-SDK#33]
I'm getting crash on login – https://space.zeo.net/g/31p34, first time I run the app it crashed on

[self postPath:@"login"
parameters:@{@"username" : username, @"password": password, @"appcode" : self.appCode}
success:^(NSDictionary *responseObject) {

Second run – everything ok, it was from Xcode 6.0 to 6.3 betas or not doesn't care.

**Comment by funkyboy** [comment]
Can you please provide a bit more details? For example how is BaasBox initialized?

**Comment by invoodoo** [comment]
Hi,
There are a screenshots what I'm doing and what happens: https://space.zeo.net/g/5k6ly

On first run self.appCode = nil, but I'm setup it before the login. nothing changing just rerun and it works perfect.

**Comment by funkyboy** [comment]
Did you set the appCode as documented here? http://www.baasbox.com/documentation/?objective_c#ios-sdk

**Comment by invoodoo** [comment]
Yes, of course: [BaasBox setBaseURL:kServerURL appCode:kAppCode]; It doesn't work on first build if app isn't on device. After that just run app from device – all good.

**Comment by funkyboy** [comment]
I suspect there's one call that gets triggered before you call `setBaseURL:appCode:`. Are you calling it at the top of `application:didFinishLaunchingWithOptions:` ?

**Comment by invoodoo** [comment]
I checked that it runs before the requests, but I'd used it in singleton on init. Moved to AppDelegate – works perfect. Thanks.
