### ISSUE TITLE
+(void) fetchCountForObjectsWithParameters:(NSDictionary *)parameters completion:(...)

### ISSUE THREAD

**Issue by surpher** [baasbox/iOS-SDK#40]
Would be something the backend could do rather than the client.

**Comment by giastfader** [comment]
The operation is actually done by the server with a specific API.
The SDK calls it: https://github.com/baasbox/iOS-SDK/blob/master/BaasBox-iOS-SDK/BAAClient.m#L454

**Comment by surpher** [comment]
I'm aware of that one, and that's fine.
What if I want to count only documents `["where" : "distance(latitude, longitude, 100, 40)" < 1500]` and I have about 15 000 of objects, I'd rather check if I even want to fetch so many in the first place... and show a message something like: "hey buddy, I fetched only 100 locations, but there's actually 3982 in the area you're searching. Why don't you zoom in?".

**Comment by funkyboy** [comment]
Each response has a max number of returned objects, even if you don't specify the [recordsPerPage](http://www.baasbox.com/documentation/?shell#pagination-and-query-criteria) param.
The default value in the SDK is [50](https://github.com/baasbox/iOS-SDK/blob/master/BaasBox-iOS-SDK/BAAClient.m#L23)
